### PR TITLE
Use -Clink-self-contained to avoid wrapper scripts

### PR DESCRIPTION
**Pull request by japaric**
this is a continuation of PR #2 
now that cross PR 497 has landed we don't need to build a docker image in CI :tada:

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]
This looks great! So we'll need to wait for 0.2.1 to adopt it for Vector?

**Comment by japaric** [comment]
> This looks great! So we'll need to wait for 0.2.1 to adopt it for Vector?

it's not necessary to wait for new cross release. vector CI is using the "latest" tag (*) of cross images so it already has access to the changes required to remove the rustc wrappers. Should I prepare a PR to remove the rustc wrappers from the vector repo?

(*) I would, however, recommend using the images tagged "0.2.2" when they are released. The "latest" tag is a "moving target" that's updated every time a cross PR is merged so, in theory, the vector repo could be hit by a breaking change at some point in the future (e.g. when the cross repo starts landing breaking changes in tree, in preparation for cross 0.3.0). Tag "0.2.2" (and other version tags) are immutable so you don't have to worry about them changing over night.

(`rustembedded/cross:x86_64-unknown-linux-musl` is the "latest" tag (moving target). `rustembedded/cross:x86_64-unknown-linux-musl-0.2.1` is a versioned tag (immutable))

**Comment by japaric** [comment]
(P.S. I don't have permissions to merge PRs in this repo. Feel to merge this one whenever)

**Comment by jamtur01** [comment]
@japaric Please feel free to raise a PR on vector! Thanks.

**Pull request merged**
